[versions]
agp = "8.3.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
googleServices = "4.4.1"
firebaseDatabase = "20.3.1"
firebaseStorage = "20.3.0"
glide = "5.0.0-rc01"
palette = "1.0.0"
media = "1.7.0"
firebaseAuth = "22.3.1"
runner = "1.6.0-alpha07"
rules = "1.6.0-alpha04"
mockitoCore = "5.12.0"
coreKtx = "1.6.0-alpha06"
monitor = "1.7.0-alpha05"
fragmentTesting = "1.8.0-alpha02"
fragmentTestingManifest = "1.8.0-alpha02"
core = "1.6.0-alpha06"
uiautomator = "2.3.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "googleServices" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage", version.ref = "firebaseStorage" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
palette = { group = "androidx.palette", name = "palette", version.ref = "palette" }
media = { group = "androidx.media", name = "media", version.ref = "media" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
rules = { group = "androidx.test", name = "rules", version.ref = "rules" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoCore" }
core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "coreKtx" }
monitor = { group = "androidx.test", name = "monitor", version.ref = "monitor" }
fragment-testing = { group = "androidx.fragment", name = "fragment-testing", version.ref = "fragmentTesting" }
fragment-testing-manifest = { group = "androidx.fragment", name = "fragment-testing-manifest", version.ref = "fragmentTestingManifest" }
core = { group = "androidx.test", name = "core", version.ref = "core" }
uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

